/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthenticatedWeaningRouteImport } from './routes/_authenticated/weaning'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedStorefrontRouteImport } from './routes/_authenticated/storefront'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPedigreeRouteImport } from './routes/_authenticated/pedigree'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMilkRouteImport } from './routes/_authenticated/milk'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedGrowthRouteImport } from './routes/_authenticated/growth'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedEnterpriseRouteImport } from './routes/_authenticated/enterprise'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedChoosePlanRouteImport } from './routes/_authenticated/choose-plan'
import { Route as AuthenticatedBreedingRouteImport } from './routes/_authenticated/breeding'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedAnimalsRouteImport } from './routes/_authenticated/animals'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedWeaningRoute = AuthenticatedWeaningRouteImport.update({
  id: '/weaning',
  path: '/weaning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStorefrontRoute = AuthenticatedStorefrontRouteImport.update({
  id: '/storefront',
  path: '/storefront',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedigreeRoute = AuthenticatedPedigreeRouteImport.update({
  id: '/pedigree',
  path: '/pedigree',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMilkRoute = AuthenticatedMilkRouteImport.update({
  id: '/milk',
  path: '/milk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGrowthRoute = AuthenticatedGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnterpriseRoute = AuthenticatedEnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChoosePlanRoute = AuthenticatedChoosePlanRouteImport.update({
  id: '/choose-plan',
  path: '/choose-plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBreedingRoute = AuthenticatedBreedingRouteImport.update({
  id: '/breeding',
  path: '/breeding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnimalsRoute = AuthenticatedAnimalsRouteImport.update({
  id: '/animals',
  path: '/animals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/animals': typeof AuthenticatedAnimalsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/breeding': typeof AuthenticatedBreedingRoute
  '/choose-plan': typeof AuthenticatedChoosePlanRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enterprise': typeof AuthenticatedEnterpriseRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/growth': typeof AuthenticatedGrowthRoute
  '/health': typeof AuthenticatedHealthRoute
  '/hr': typeof AuthenticatedHrRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/milk': typeof AuthenticatedMilkRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/pedigree': typeof AuthenticatedPedigreeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/storefront': typeof AuthenticatedStorefrontRoute
  '/support': typeof AuthenticatedSupportRoute
  '/weaning': typeof AuthenticatedWeaningRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/invite/$token': typeof InviteTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/animals': typeof AuthenticatedAnimalsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/breeding': typeof AuthenticatedBreedingRoute
  '/choose-plan': typeof AuthenticatedChoosePlanRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enterprise': typeof AuthenticatedEnterpriseRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/growth': typeof AuthenticatedGrowthRoute
  '/health': typeof AuthenticatedHealthRoute
  '/hr': typeof AuthenticatedHrRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/milk': typeof AuthenticatedMilkRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/pedigree': typeof AuthenticatedPedigreeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/storefront': typeof AuthenticatedStorefrontRoute
  '/support': typeof AuthenticatedSupportRoute
  '/weaning': typeof AuthenticatedWeaningRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/invite/$token': typeof InviteTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/animals': typeof AuthenticatedAnimalsRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/breeding': typeof AuthenticatedBreedingRoute
  '/_authenticated/choose-plan': typeof AuthenticatedChoosePlanRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/enterprise': typeof AuthenticatedEnterpriseRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/growth': typeof AuthenticatedGrowthRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/hr': typeof AuthenticatedHrRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/milk': typeof AuthenticatedMilkRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/pedigree': typeof AuthenticatedPedigreeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/storefront': typeof AuthenticatedStorefrontRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/weaning': typeof AuthenticatedWeaningRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/invite/$token': typeof InviteTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/verify-email'
    | '/admin'
    | '/analytics'
    | '/animals'
    | '/assets'
    | '/breeding'
    | '/choose-plan'
    | '/customers'
    | '/dashboard'
    | '/enterprise'
    | '/finance'
    | '/growth'
    | '/health'
    | '/hr'
    | '/inventory'
    | '/marketplace'
    | '/milk'
    | '/notifications'
    | '/orders'
    | '/pedigree'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/storefront'
    | '/support'
    | '/weaning'
    | '/auth/forgot'
    | '/invite/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/verify-email'
    | '/admin'
    | '/analytics'
    | '/animals'
    | '/assets'
    | '/breeding'
    | '/choose-plan'
    | '/customers'
    | '/dashboard'
    | '/enterprise'
    | '/finance'
    | '/growth'
    | '/health'
    | '/hr'
    | '/inventory'
    | '/marketplace'
    | '/milk'
    | '/notifications'
    | '/orders'
    | '/pedigree'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/storefront'
    | '/support'
    | '/weaning'
    | '/auth/forgot'
    | '/invite/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/verify-email'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/animals'
    | '/_authenticated/assets'
    | '/_authenticated/breeding'
    | '/_authenticated/choose-plan'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/enterprise'
    | '/_authenticated/finance'
    | '/_authenticated/growth'
    | '/_authenticated/health'
    | '/_authenticated/hr'
    | '/_authenticated/inventory'
    | '/_authenticated/marketplace'
    | '/_authenticated/milk'
    | '/_authenticated/notifications'
    | '/_authenticated/orders'
    | '/_authenticated/pedigree'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/storefront'
    | '/_authenticated/support'
    | '/_authenticated/weaning'
    | '/auth/forgot'
    | '/invite/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/weaning': {
      id: '/_authenticated/weaning'
      path: '/weaning'
      fullPath: '/weaning'
      preLoaderRoute: typeof AuthenticatedWeaningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storefront': {
      id: '/_authenticated/storefront'
      path: '/storefront'
      fullPath: '/storefront'
      preLoaderRoute: typeof AuthenticatedStorefrontRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedigree': {
      id: '/_authenticated/pedigree'
      path: '/pedigree'
      fullPath: '/pedigree'
      preLoaderRoute: typeof AuthenticatedPedigreeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/milk': {
      id: '/_authenticated/milk'
      path: '/milk'
      fullPath: '/milk'
      preLoaderRoute: typeof AuthenticatedMilkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/growth': {
      id: '/_authenticated/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof AuthenticatedGrowthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enterprise': {
      id: '/_authenticated/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof AuthenticatedEnterpriseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/choose-plan': {
      id: '/_authenticated/choose-plan'
      path: '/choose-plan'
      fullPath: '/choose-plan'
      preLoaderRoute: typeof AuthenticatedChoosePlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/breeding': {
      id: '/_authenticated/breeding'
      path: '/breeding'
      fullPath: '/breeding'
      preLoaderRoute: typeof AuthenticatedBreedingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/animals': {
      id: '/_authenticated/animals'
      path: '/animals'
      fullPath: '/animals'
      preLoaderRoute: typeof AuthenticatedAnimalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAnimalsRoute: typeof AuthenticatedAnimalsRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedBreedingRoute: typeof AuthenticatedBreedingRoute
  AuthenticatedChoosePlanRoute: typeof AuthenticatedChoosePlanRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEnterpriseRoute: typeof AuthenticatedEnterpriseRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedGrowthRoute: typeof AuthenticatedGrowthRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedHrRoute: typeof AuthenticatedHrRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedMilkRoute: typeof AuthenticatedMilkRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPedigreeRoute: typeof AuthenticatedPedigreeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStorefrontRoute: typeof AuthenticatedStorefrontRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedWeaningRoute: typeof AuthenticatedWeaningRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAnimalsRoute: AuthenticatedAnimalsRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedBreedingRoute: AuthenticatedBreedingRoute,
  AuthenticatedChoosePlanRoute: AuthenticatedChoosePlanRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEnterpriseRoute: AuthenticatedEnterpriseRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedGrowthRoute: AuthenticatedGrowthRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedHrRoute: AuthenticatedHrRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedMilkRoute: AuthenticatedMilkRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPedigreeRoute: AuthenticatedPedigreeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStorefrontRoute: AuthenticatedStorefrontRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedWeaningRoute: AuthenticatedWeaningRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
